apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: only-allow-wisecow-exec
  namespace: wisecow
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
      - path: /usr/src/app/wisecow.sh
  action: Allow

  kubectl -n wisecow exec -it wisecow-depl-58fd77fc7-4vv9w  -- /bin/sh -c 'echo hello'